version: 1.2
workflows:
   - name: allele_freq
     subclass: CWL
     publish: true
     primaryDescriptorPath: /tools/allele_freq.cwl
     testParameterFiles:
         - /tools/test/allele_freq.test.json
   - name: simulate_correlated_outcomes
     subclass: CWL
     publish: true
     primaryDescriptorPath: /tools/outcomes_in_parallel.cwl
     testParameterFiles:
         - /tools/test/outcomes_in_parallel.test.json
   - name: iterative_ld_pruning
     subclass: CWL
     publish: true
     primaryDescriptorPath: /tools/iterative_ld_pruning.cwl
     testParameterFiles:
         - /tools/test/iterative_ld_pruning.test.json
   - name: simulate_variant_effects
     subclass: CWL
     publish: true
     primaryDescriptorPath: /tools/test_variant_effects.cwl
     testParameterFiles:
         - /tools/test/test_variant_effects.test.json
   - name: simulate_outcomes_with_effects
     subclass: CWL
     publish: true
     primaryDescriptorPath: /tools/outcomes_with_effects.cwl
     testParameterFiles:
         - /tools/test/outcomes_with_effects.test.json
