---
title: "variant selection"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
#remotes::install_github("UW-GAC/simulate_phenotypes/simphen", upgrade=FALSE)
remotes::install_local("/sbgenomics/workspace/simulate_phenotypes/simphen", upgrade=FALSE)
library(simphen)
#library(devtools)
#load_all("/sbgenomics/workspace/simulate_phenotypes/simphen")
```

Frequency of variants in chromosome 1 in AfrAm and EurAm strata

```{r}
afr <- readRDS("/sbgenomics/project-files/freeze8_allele_freq_chr1_AfrAm.rds")
eur <- readRDS("/sbgenomics/project-files/freeze8_allele_freq_chr1_EurAm.rds")

all.equal(afr$variant.id, eur$variant.id)

freq <- rename(afr, freq.afr=alt.freq) %>%
  bind_cols(select(eur, freq.eur=alt.freq)) %>%
  filter(freq.afr > 0 | freq.eur > 0) # remove monomorphic
nrow(freq)

rm(afr, eur) # save memory
```

Select observed variants

```{r}
obs_both <- var_multiple_strata(freq$freq.afr, freq$freq.eur)
length(obs_both)
obs_afr <- var_single_stratum(freq$freq.afr, freq$freq.eur, min.freq=0.1, max.freq=0.001)
obs_eur <- var_single_stratum(freq$freq.eur, freq$freq.afr, min.freq=0.1, max.freq=0.001)
length(obs_afr)
length(obs_eur)
```

```{r}
obs_afr <- var_single_stratum(freq$freq.afr, freq$freq.eur, min.freq=0.01, max.freq=0.001)
obs_eur <- var_single_stratum(freq$freq.eur, freq$freq.afr, min.freq=0.01, max.freq=0.001)
length(obs_afr)
length(obs_eur)
```

```{r}
obs_afr <- var_single_stratum(freq$freq.afr, freq$freq.eur, min.freq=0.001, max.freq=0.0001)
obs_eur <- var_single_stratum(freq$freq.eur, freq$freq.afr, min.freq=0.001, max.freq=0.0001)
length(obs_afr)
length(obs_eur)
```


Generate outcome from covariance matrix - how long does this take?

```{r}
covmat <- GWASTools::getobj("/sbgenomics/project-files/pcrelate_kinshipMatrix_sparseDeg4_v2.RData")
# subset to only samples we are using
samples.afr <- readRDS("/sbgenomics/project-files/strata/freeze8_samples_AfrAm_2020-07-23.rds")
samples.eur <- readRDS("/sbgenomics/project-files/strata/freeze8_samples_EurAm_2020-07-23.rds")
ind <- which(rownames(covmat) %in% c(samples.afr, samples.eur))
covmat <- covmat[ind,ind]
varComp <- c(3,7)
system.time(outcome <- outcome_from_covMat_blocks(covmat, varComp))
```


Load GDS file to get genotypes

```{r}
library(SeqArray)
gds <- seqOpen("/sbgenomics/project-files/freeze8_gds/freeze.8.pass_poly.gtonly.minDP0_chr1.gds")
seqSetFilter(gds, sample.id=c(samples.afr, samples.eur))
```
